dist: bionic

language: go

go:
  - 1.13.x

sudo: true

addons:
  apt:
    update: true

before_install:                                                                 
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh  
  - dep ensure
  - sudo apt install poppler-utils wv unrtf tidy

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
